project:
  type: website
  output-dir: docs

website:
  title: "Regina Lisinker"
  favicon: "img/laser_logo.png" 
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - href: research.qmd
        text: Research
      - href: teach.qmd
        text: Teaching

format:
  html:
    page-layout: full
    theme: 
      # - cosmo
      - "assets/theme.scss"
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Roboto:ital@0;1&display=swap" rel="stylesheet"> 
    toc: false
    mainfont: "Roboto"



