---
title: "Research"
format:
  html:
    anchor-sections: false
---

Here's what I've been up to at the University of Minnesota! 

#### Lab Member | Lab Advancing Statistics Education Research [(LASER)](https://laser-umn.github.io/)
  - Collaborative research with statistics education researchers at the University of Minnesota
  - Curriculum development: [Algorithmic Modeling](https://laser-umn.github.io/posts/alg-mod.html)
      - Building on past research teaching CART algorithms, LASER is currently designing activities focusing on the kNN algorithm
      - I've been helping to develop educational materials to teach classification methods and introductory machine learning techniques
      - Putting my love of powerpoint templates to good use, I was responsible for formatting and styling templates to design high-quality presentations
      - See our [workshop materials](https://laser-umn.github.io/sessions/knn-classification.html) from MCTM '24!
  - Curriculum development: Data Visualization
      - I'm working to help reorganize and update the course activities for EPSY 1261: Understanding Data Stories through Visualization & Computing  
      - This is partially in preparation for my Ph.D. milestone/dissertation work on the comprehension and creation of [data visualization](https://rlisinker.com/projects/data-viz.html) 

#### Graduate Assistant | College in the Schools [(CIS)](https://ccaps.umn.edu/college-in-the-schools/basic-and-applied-statistics): Statistics Cohort
##### Faculty Coordinator
  - I help plan and implement day-long professional development training sessions three times each year for the statistics cohort of CIS high school teachers 
      - Professional development topics include: data wrangling pseudo code, item writing, inter-rater reliability, and item analysis
  - Part of this position means I get to observe instructors to provide feedback on classroom engagement strategies two to three times each semester
  - See our [workshop materials](https://laser-umn.github.io/sessions/be-above-average.html) from MCTM '24 to learn more about the course!

#### Research Assistant | [DataX](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2101413): Exploring Justice-Oriented Data Science with Secondary School Studentss
##### Data Analysis 
  - I've been getting to explore qualitative coding of video through this NSF-funded project 
      - Video is obtained from a secondary school social studies class learning data science topics
  - As part of this position, I've also been responsible for assembling a literature review of history and data science education research

#### Research Assistant | Data Science-Wrangle Analyze Visualize [(DSC-WAV)](https://dsc-wav.github.io/www/index.html): Code Review 
#####  Evaluation Team
  - I created educational resources for data science students learning how to review code (code review checklist, style guide considerations, etc.) and surveyed students on their code review processes
  - Learn more about my [MA Thesis work here!](https://rlisinker.com/projects/code-review.html)
  
#### Other Projects
##### Attitudes Towards Statistics
  - My first project as an MA student was looking into student attitudes towards statistics through a qualitative lens
  - I might return to this at a later date once I have a chance to collect fresh data and implement the lessons I've learned since my first semester of grad school 
  - Check out [this page](https://rlisinker.com/projects/attitudes.html) to see my first research poster and my musings on attitudes towards statistics
  
  
  
  